### ISSUE TITLE
Расширение таблицы врач

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-backend#15]
К существующей таблице, нужно добавить информацию о опыте работы, специализации

**Comment by G3rkul3s** [comment]
таблица расширена
![изображение](https://user-images.githubusercontent.com/68826041/141154835-b520053d-fd60-425c-bc57-0c5eb0d1c3dc.png)

**Comment by reshat** [comment]
![Screenshot_348](https://user-images.githubusercontent.com/1532675/142378296-d3d2cf5c-26a8-450a-88ba-cf9da0de603a.png)
Данные появились на проде
