### ISSUE TITLE
Добавление входа

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-backend#16]
1. Создать с помощью spring security связку пароль логин. 
2. Обработать получение пароля и логина с фронта
3. Отправить результат на фронт

**Comment by Reddrok** [comment]
Добавил авторизацию и аутентификацию. Теперь логины и пароли хранятся в БД. После авторизации фронту даётся сессия с правами, соответствующими роли пользователя. Для проверки сделал так, что запрос "../test" может выполнить только пациент. 
Отправка запроса "../test" без авторизации:
![image](https://user-images.githubusercontent.com/91416355/140617880-3870dfa2-ef5b-4ec1-981e-35ec4561bf31.png)

Отправка запроса "../test" с авторизацией:
![image](https://user-images.githubusercontent.com/91416355/140617812-333c622b-b730-4836-aeaf-2459d66e7fda.png)

**Comment by Reddrok** [comment]
Добавил авторизацию и аутентификацию. Для теста сделал запрос "../test" доступным только зарегистрированным пациентам. Для аутентификации необходимо отправить post запрос "../login" с json строкой, содержащей username и password. 
При выполнении запроса "../test" без аутентификации:
![image](https://user-images.githubusercontent.com/91416355/140989562-08f208a6-7f37-4213-85e1-2055dadc74db.png)
Выполнение запроса "../login"(после авторизации backend автоматически выполняет последний запрос, который был отклонен из-за недостатка прав, поэтому сразу выполнился запрос "../test", но, конечно, можно и сразу выполнять запрос "../login" и потом делать всё необходимое):
![image](https://user-images.githubusercontent.com/91416355/140990375-1eb224e9-41d7-463b-9209-89b4b8b6a449.png)
Также решил проблему с cors

**Comment by reshat** [comment]
![Screenshot_345](https://user-images.githubusercontent.com/1532675/142374634-af4f6565-8f82-4c26-b05c-fcbe2c5653a9.png)
Без аутентификации тестовых данных нет
![Screenshot_346](https://user-images.githubusercontent.com/1532675/142374680-7b03283f-461e-4b97-837b-04511df077bc.png)
После ввода логина пароля данные приходят
![Screenshot_346](https://user-images.githubusercontent.com/1532675/142374769-323c8ced-388d-4228-8e7d-5c2125954e49.png)

![Screenshot_347](https://user-images.githubusercontent.com/1532675/142374781-1ba4bd0e-62b0-4748-84b9-4165a47a459f.png)
