### ISSUE TITLE
Убрать обязательный вход

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-backend#17]
В случае, если пользователь не вошел в учетную запись, ему все еще должен быть доступен функционал сайта. Для этого придется настроить spring security.

**Comment by Reddrok** [comment]
Вернул Spring Security, но добавил возможность пользоваться приложением без авторизации
![image](https://user-images.githubusercontent.com/91416355/140333846-3a1146bb-3736-4a51-8b31-0762ab6f4bd2.png)

**Comment by reshat** [comment]
![Screenshot_278](https://user-images.githubusercontent.com/1532675/140372495-7263aba7-8119-4066-9481-310927468046.png)
Проверил
