### ISSUE TITLE
Регистрация нового пользователя

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-backend#18]
Добавить возможность регистрации пользователя, с фронта будет получена следующая информация:
логин, пароль, фио, почта

**Comment by Reddrok** [comment]
Добавил регистрацию. Запрос и его структуру можно увидеть на следующем скриншоте.
![image](https://user-images.githubusercontent.com/91416355/143914626-fc0891f5-f061-4497-b2d4-cd83e02c0466.png)
В случае попытки регистрации пользователя с логином или почтой, которую уже имеет другой пользователь, то в регистрации будет отказано.

**Comment by reshat** [comment]
Данная функция тестируется интеграционными тестами
![Screenshot_444](https://user-images.githubusercontent.com/1532675/145380688-744b9696-995c-4137-9e0f-467b4f9b4813.png)
