### ISSUE TITLE
Календарь врача

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-backend#19]
По запросу, должна быть предоставлена информация фронту о том, в какие дни НА ЭТОЙ И СЛЕДУЮЩЕЙ НЕДЕЛЕ и сколько будет работать выбранный врач.

**Comment by G3rkul3s** [comment]
расписание:
![изображение](https://user-images.githubusercontent.com/68826041/141692471-87cafd85-b36b-4bf5-b57f-f32be82967c3.png)

результат запроса:
![изображение](https://user-images.githubusercontent.com/68826041/141692453-bc33d18a-d989-429d-a38a-6fd1e65fa3c7.png)
