### ISSUE TITLE
Запись пациента 

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-backend#32]
Нужно обработать запрос на запись пациента. Пациент это зарегистрированный пользователь, ему будут доступно расписание врачей, выбрав свободное время от врача, пациент записывается на определенный час, при этом, он может одновременно иметь только две записи.
Запрос может быть отправлен либо пациентом, либо врачом
Запрос будет состоять из id врача, id пациента, время записи, длительность записи (по умолчанию 1 час, более 1 часа может поставить только сам врач)

**Comment by G3rkul3s** [comment]
Добавлен запрос на запись пациента:
![изображение](https://user-images.githubusercontent.com/68826041/144618423-391918f2-edc6-4553-8a32-29b6078f7445.png)

**Comment by G3rkul3s** [comment]
UPDATE: appointment_duration больше не отправляется
