### ISSUE TITLE
Редактирование рабочих часов

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-backend#33]
Администратор может поменять часы работы любого врача и только он может делать этот запрос
Запрос состоит из id врача, дата, начало работы, конец работы

**Comment by Reddrok** [comment]
Добавил роль админа и запрос, который меняет часы работы выбранного врача. Демонстрация выполнения запроса и его структура приведены ниже. Для выполнения запроса необходимо обладать ролью администратора.
![image](https://user-images.githubusercontent.com/91416355/144990912-3b8cd7c4-aed2-42dd-ba92-f90db8e0dcb1.png)

![image](https://user-images.githubusercontent.com/91416355/144994348-744ed6ad-cea3-4e7b-aac6-c372a1f4e8e6.png)

![image](https://user-images.githubusercontent.com/91416355/144994471-f9e3abb5-abaa-47f1-87f5-af8670858c77.png)

При указании неверного id или date, запрос выдаёт ошибку:
![image](https://user-images.githubusercontent.com/91416355/144994839-d28af984-5d6a-4fe3-926b-9535b05df8bd.png)
