### ISSUE TITLE
Добавление записи пациенту

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-backend#34]
Врач может оставить некоторую запись и пациенте
Запрос будет содержать id врача, id пациента, дата, запись(строка содержащая заключение врача по приему)

**Comment by G3rkul3s** [comment]
добавлен запрос:
![изображение](https://user-images.githubusercontent.com/68826041/144296690-226bbd29-8001-4921-b064-67ea7e4dc470.png)
ВАЖНО!!!: дата распознается только в таком формате "yyyy-MM-dd"
результат:
![изображение](https://user-images.githubusercontent.com/68826041/144296993-1df67d30-abf0-42a5-8408-84db16f171dd.png)
