### ISSUE TITLE
Получение результата приема

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-backend#35]
Пациент может получить по запросу все записи оставленные пациенту
Запрос содержит id пациента
Ответ ФИО врача, дата, запись

**Comment by Reddrok** [comment]
Добавил возможность получать по id пациента ФИО врача, дату создания записи и саму запись.
Запрос и его структура приведена на следующем скриншоте:
![image](https://user-images.githubusercontent.com/91416355/144614616-1a11c3b5-6cee-4b7a-8208-80b54d00cfee.png)
Для выполнения запроса нужно войти в аккаунт

**Comment by reshat** [comment]
Работает
![Screenshot_445](https://user-images.githubusercontent.com/1532675/145381023-ecf2be17-bb26-4753-b01a-ce2bb05070a6.png)
