### ISSUE TITLE
Запрос о рабочих часах доктора

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-backend#45]
Необходимо получить время когда у него все еще есть свободные слоты, когда врач не работает и когда врач занят
Запрос: id доктора
Данные: timetable, это общедоступная информация

**Comment by G3rkul3s** [comment]
![изображение](https://user-images.githubusercontent.com/68826041/145401708-4767f5ee-e2af-43b9-805e-d3554665aac3.png)

**Comment by G3rkul3s** [comment]
![изображение](https://user-images.githubusercontent.com/68826041/145414126-870139ea-77d0-4de4-bc27-921cfe2d22e0.png)
