### ISSUE TITLE
Просмотор времени, на которое записан пациент 

### ISSUE THREAD

**Issue by Reddrok** [reshat/hospital-backend#56]
С фронтэнда приходит id пациента. Нужно создать запрос, который вернёт на фронт ФИО доктора, дату и время.

**Comment by Reddrok** [comment]
Структура и результат запроса можно увидеть на следующем скриншоте:
![image](https://user-images.githubusercontent.com/91416355/145619169-8f1c6d77-483c-424d-adc2-3acccd5c2ef6.png)
Для выполнения запроса нужно быть авторизированным пользователем.

**Comment by reshat** [comment]
![Screenshot_534](https://user-images.githubusercontent.com/1532675/146435777-1f7611cc-e335-4261-8f96-9039a199fe27.png)
Работает
