### ISSUE TITLE
Отправка списка врачей на front end

### ISSUE THREAD

**Issue by reshat** [reshat/hospital-backend#7]
При получении запроса от front end, необходимо сформировать и отправить список врачей на frontend в формате json или другом удобном

**Comment by Reddrok** [comment]
Добавил отправку списка врачей на front. 
Запрос "localhost:8081/doctors"
JSON имеет структуру, показанную на скриншоте
![image](https://user-images.githubusercontent.com/91416355/139593908-e184eff5-f444-421e-9eec-6b199ed5fc19.png)

**Comment by reshat** [comment]
Все работает отлично
